name: Build healthcheck

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate healthcheck files
        run: bash build-healthcheck.sh

      - name: Get date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            _healthcheck.html
            _healthcheck-without-tag.html
          tag_name: healthcheck-${{ github.run_id }}
          name: Romain MILLAN - Healthcheck - ${{ steps.date.outputs.date }}
          make_latest: true
